<?php
/**
 * SecureMessagesApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Mydex\ApiPdxSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PDX API
 *
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Mydex\ApiPdxSdk\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Mydex\ApiPdxSdk\ApiException;
use Mydex\ApiPdxSdk\Configuration;
use Mydex\ApiPdxSdk\FormDataProcessor;
use Mydex\ApiPdxSdk\HeaderSelector;
use Mydex\ApiPdxSdk\ObjectSerializer;

/**
 * SecureMessagesApi Class Doc Comment
 *
 * @category Class
 * @package  Mydex\ApiPdxSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SecureMessagesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getSecureMessageConversation' => [
            'application/json',
        ],
        'postSecureMessageReceive' => [
            'application/json',
        ],
        'postSecureMessageSend' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getSecureMessageConversation
     *
     * Retrieve all secure messages for a given conversation.
     *
     * @param  string $connection_token Member&#39;s Connection Key (required)
     * @param  string $uid The unique ID of a mydex member (required)
     * @param  string $con_id The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. (required)
     * @param  string $conversation_id The specific ID of the conversation that groups messages together (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSecureMessageConversation'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiPdxSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Mydex\ApiPdxSdk\Model\SecureMessageConversationResponse|\Mydex\ApiPdxSdk\Model\AuthErrorResponse
     */
    public function getSecureMessageConversation($connection_token, $uid, $con_id, $conversation_id, string $contentType = self::contentTypes['getSecureMessageConversation'][0])
    {
        list($response) = $this->getSecureMessageConversationWithHttpInfo($connection_token, $uid, $con_id, $conversation_id, $contentType);
        return $response;
    }

    /**
     * Operation getSecureMessageConversationWithHttpInfo
     *
     * Retrieve all secure messages for a given conversation.
     *
     * @param  string $connection_token Member&#39;s Connection Key (required)
     * @param  string $uid The unique ID of a mydex member (required)
     * @param  string $con_id The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. (required)
     * @param  string $conversation_id The specific ID of the conversation that groups messages together (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSecureMessageConversation'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiPdxSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Mydex\ApiPdxSdk\Model\SecureMessageConversationResponse|\Mydex\ApiPdxSdk\Model\AuthErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSecureMessageConversationWithHttpInfo($connection_token, $uid, $con_id, $conversation_id, string $contentType = self::contentTypes['getSecureMessageConversation'][0])
    {
        $request = $this->getSecureMessageConversationRequest($connection_token, $uid, $con_id, $conversation_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiPdxSdk\Model\SecureMessageConversationResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiPdxSdk\Model\AuthErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Mydex\ApiPdxSdk\Model\SecureMessageConversationResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiPdxSdk\Model\SecureMessageConversationResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiPdxSdk\Model\AuthErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getSecureMessageConversationAsync
     *
     * Retrieve all secure messages for a given conversation.
     *
     * @param  string $connection_token Member&#39;s Connection Key (required)
     * @param  string $uid The unique ID of a mydex member (required)
     * @param  string $con_id The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. (required)
     * @param  string $conversation_id The specific ID of the conversation that groups messages together (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSecureMessageConversation'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSecureMessageConversationAsync($connection_token, $uid, $con_id, $conversation_id, string $contentType = self::contentTypes['getSecureMessageConversation'][0])
    {
        return $this->getSecureMessageConversationAsyncWithHttpInfo($connection_token, $uid, $con_id, $conversation_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getSecureMessageConversationAsyncWithHttpInfo
     *
     * Retrieve all secure messages for a given conversation.
     *
     * @param  string $connection_token Member&#39;s Connection Key (required)
     * @param  string $uid The unique ID of a mydex member (required)
     * @param  string $con_id The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. (required)
     * @param  string $conversation_id The specific ID of the conversation that groups messages together (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSecureMessageConversation'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSecureMessageConversationAsyncWithHttpInfo($connection_token, $uid, $con_id, $conversation_id, string $contentType = self::contentTypes['getSecureMessageConversation'][0])
    {
        $returnType = '\Mydex\ApiPdxSdk\Model\SecureMessageConversationResponse';
        $request = $this->getSecureMessageConversationRequest($connection_token, $uid, $con_id, $conversation_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getSecureMessageConversation'
     *
     * @param  string $connection_token Member&#39;s Connection Key (required)
     * @param  string $uid The unique ID of a mydex member (required)
     * @param  string $con_id The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. (required)
     * @param  string $conversation_id The specific ID of the conversation that groups messages together (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSecureMessageConversation'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getSecureMessageConversationRequest($connection_token, $uid, $con_id, $conversation_id, string $contentType = self::contentTypes['getSecureMessageConversation'][0])
    {

        // verify the required parameter 'connection_token' is set
        if ($connection_token === null || (is_array($connection_token) && count($connection_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $connection_token when calling getSecureMessageConversation'
            );
        }

        // verify the required parameter 'uid' is set
        if ($uid === null || (is_array($uid) && count($uid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $uid when calling getSecureMessageConversation'
            );
        }

        // verify the required parameter 'con_id' is set
        if ($con_id === null || (is_array($con_id) && count($con_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $con_id when calling getSecureMessageConversation'
            );
        }

        // verify the required parameter 'conversation_id' is set
        if ($conversation_id === null || (is_array($conversation_id) && count($conversation_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $conversation_id when calling getSecureMessageConversation'
            );
        }


        $resourcePath = '/secure-messages/conversation';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $uid,
            'uid', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $con_id,
            'con_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $conversation_id,
            'conversation_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);

        // header params
        if ($connection_token !== null) {
            $headerParams['Connection-Token'] = ObjectSerializer::toHeaderValue($connection_token);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postSecureMessageReceive
     *
     * Supports sending a message to the member&#39;s PDS.
     *
     * @param  string $connection_token Member&#39;s Connection Key (required)
     * @param  string $uid The unique ID of a mydex member (required)
     * @param  string $con_id The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. (required)
     * @param  \Mydex\ApiPdxSdk\Model\SecureMessageReceiveRequest|null $secure_message_receive_request secure_message_receive_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postSecureMessageReceive'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiPdxSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Mydex\ApiPdxSdk\Model\CreateResponse|\Mydex\ApiPdxSdk\Model\ErrorResponse|\Mydex\ApiPdxSdk\Model\AuthErrorResponse
     */
    public function postSecureMessageReceive($connection_token, $uid, $con_id, $secure_message_receive_request = null, string $contentType = self::contentTypes['postSecureMessageReceive'][0])
    {
        list($response) = $this->postSecureMessageReceiveWithHttpInfo($connection_token, $uid, $con_id, $secure_message_receive_request, $contentType);
        return $response;
    }

    /**
     * Operation postSecureMessageReceiveWithHttpInfo
     *
     * Supports sending a message to the member&#39;s PDS.
     *
     * @param  string $connection_token Member&#39;s Connection Key (required)
     * @param  string $uid The unique ID of a mydex member (required)
     * @param  string $con_id The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. (required)
     * @param  \Mydex\ApiPdxSdk\Model\SecureMessageReceiveRequest|null $secure_message_receive_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postSecureMessageReceive'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiPdxSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Mydex\ApiPdxSdk\Model\CreateResponse|\Mydex\ApiPdxSdk\Model\ErrorResponse|\Mydex\ApiPdxSdk\Model\AuthErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function postSecureMessageReceiveWithHttpInfo($connection_token, $uid, $con_id, $secure_message_receive_request = null, string $contentType = self::contentTypes['postSecureMessageReceive'][0])
    {
        $request = $this->postSecureMessageReceiveRequest($connection_token, $uid, $con_id, $secure_message_receive_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiPdxSdk\Model\CreateResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiPdxSdk\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiPdxSdk\Model\AuthErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Mydex\ApiPdxSdk\Model\CreateResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiPdxSdk\Model\CreateResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiPdxSdk\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiPdxSdk\Model\AuthErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation postSecureMessageReceiveAsync
     *
     * Supports sending a message to the member&#39;s PDS.
     *
     * @param  string $connection_token Member&#39;s Connection Key (required)
     * @param  string $uid The unique ID of a mydex member (required)
     * @param  string $con_id The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. (required)
     * @param  \Mydex\ApiPdxSdk\Model\SecureMessageReceiveRequest|null $secure_message_receive_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postSecureMessageReceive'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postSecureMessageReceiveAsync($connection_token, $uid, $con_id, $secure_message_receive_request = null, string $contentType = self::contentTypes['postSecureMessageReceive'][0])
    {
        return $this->postSecureMessageReceiveAsyncWithHttpInfo($connection_token, $uid, $con_id, $secure_message_receive_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postSecureMessageReceiveAsyncWithHttpInfo
     *
     * Supports sending a message to the member&#39;s PDS.
     *
     * @param  string $connection_token Member&#39;s Connection Key (required)
     * @param  string $uid The unique ID of a mydex member (required)
     * @param  string $con_id The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. (required)
     * @param  \Mydex\ApiPdxSdk\Model\SecureMessageReceiveRequest|null $secure_message_receive_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postSecureMessageReceive'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postSecureMessageReceiveAsyncWithHttpInfo($connection_token, $uid, $con_id, $secure_message_receive_request = null, string $contentType = self::contentTypes['postSecureMessageReceive'][0])
    {
        $returnType = '\Mydex\ApiPdxSdk\Model\CreateResponse';
        $request = $this->postSecureMessageReceiveRequest($connection_token, $uid, $con_id, $secure_message_receive_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postSecureMessageReceive'
     *
     * @param  string $connection_token Member&#39;s Connection Key (required)
     * @param  string $uid The unique ID of a mydex member (required)
     * @param  string $con_id The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. (required)
     * @param  \Mydex\ApiPdxSdk\Model\SecureMessageReceiveRequest|null $secure_message_receive_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postSecureMessageReceive'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function postSecureMessageReceiveRequest($connection_token, $uid, $con_id, $secure_message_receive_request = null, string $contentType = self::contentTypes['postSecureMessageReceive'][0])
    {

        // verify the required parameter 'connection_token' is set
        if ($connection_token === null || (is_array($connection_token) && count($connection_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $connection_token when calling postSecureMessageReceive'
            );
        }

        // verify the required parameter 'uid' is set
        if ($uid === null || (is_array($uid) && count($uid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $uid when calling postSecureMessageReceive'
            );
        }

        // verify the required parameter 'con_id' is set
        if ($con_id === null || (is_array($con_id) && count($con_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $con_id when calling postSecureMessageReceive'
            );
        }



        $resourcePath = '/secure-messages/receive';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $uid,
            'uid', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $con_id,
            'con_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);

        // header params
        if ($connection_token !== null) {
            $headerParams['Connection-Token'] = ObjectSerializer::toHeaderValue($connection_token);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($secure_message_receive_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($secure_message_receive_request));
            } else {
                $httpBody = $secure_message_receive_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postSecureMessageSend
     *
     * Supports sending a message from the member&#39;s PDS.
     *
     * @param  string $connection_token Member&#39;s Connection Key (required)
     * @param  string $uid The unique ID of a mydex member (required)
     * @param  string $con_id The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. (required)
     * @param  \Mydex\ApiPdxSdk\Model\SecureMessageSendRequest|null $secure_message_send_request secure_message_send_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postSecureMessageSend'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiPdxSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Mydex\ApiPdxSdk\Model\CreateResponse|\Mydex\ApiPdxSdk\Model\ErrorResponse|\Mydex\ApiPdxSdk\Model\AuthErrorResponse
     */
    public function postSecureMessageSend($connection_token, $uid, $con_id, $secure_message_send_request = null, string $contentType = self::contentTypes['postSecureMessageSend'][0])
    {
        list($response) = $this->postSecureMessageSendWithHttpInfo($connection_token, $uid, $con_id, $secure_message_send_request, $contentType);
        return $response;
    }

    /**
     * Operation postSecureMessageSendWithHttpInfo
     *
     * Supports sending a message from the member&#39;s PDS.
     *
     * @param  string $connection_token Member&#39;s Connection Key (required)
     * @param  string $uid The unique ID of a mydex member (required)
     * @param  string $con_id The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. (required)
     * @param  \Mydex\ApiPdxSdk\Model\SecureMessageSendRequest|null $secure_message_send_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postSecureMessageSend'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiPdxSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Mydex\ApiPdxSdk\Model\CreateResponse|\Mydex\ApiPdxSdk\Model\ErrorResponse|\Mydex\ApiPdxSdk\Model\AuthErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function postSecureMessageSendWithHttpInfo($connection_token, $uid, $con_id, $secure_message_send_request = null, string $contentType = self::contentTypes['postSecureMessageSend'][0])
    {
        $request = $this->postSecureMessageSendRequest($connection_token, $uid, $con_id, $secure_message_send_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiPdxSdk\Model\CreateResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiPdxSdk\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiPdxSdk\Model\AuthErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Mydex\ApiPdxSdk\Model\CreateResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiPdxSdk\Model\CreateResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiPdxSdk\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiPdxSdk\Model\AuthErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation postSecureMessageSendAsync
     *
     * Supports sending a message from the member&#39;s PDS.
     *
     * @param  string $connection_token Member&#39;s Connection Key (required)
     * @param  string $uid The unique ID of a mydex member (required)
     * @param  string $con_id The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. (required)
     * @param  \Mydex\ApiPdxSdk\Model\SecureMessageSendRequest|null $secure_message_send_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postSecureMessageSend'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postSecureMessageSendAsync($connection_token, $uid, $con_id, $secure_message_send_request = null, string $contentType = self::contentTypes['postSecureMessageSend'][0])
    {
        return $this->postSecureMessageSendAsyncWithHttpInfo($connection_token, $uid, $con_id, $secure_message_send_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postSecureMessageSendAsyncWithHttpInfo
     *
     * Supports sending a message from the member&#39;s PDS.
     *
     * @param  string $connection_token Member&#39;s Connection Key (required)
     * @param  string $uid The unique ID of a mydex member (required)
     * @param  string $con_id The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. (required)
     * @param  \Mydex\ApiPdxSdk\Model\SecureMessageSendRequest|null $secure_message_send_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postSecureMessageSend'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postSecureMessageSendAsyncWithHttpInfo($connection_token, $uid, $con_id, $secure_message_send_request = null, string $contentType = self::contentTypes['postSecureMessageSend'][0])
    {
        $returnType = '\Mydex\ApiPdxSdk\Model\CreateResponse';
        $request = $this->postSecureMessageSendRequest($connection_token, $uid, $con_id, $secure_message_send_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postSecureMessageSend'
     *
     * @param  string $connection_token Member&#39;s Connection Key (required)
     * @param  string $uid The unique ID of a mydex member (required)
     * @param  string $con_id The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. (required)
     * @param  \Mydex\ApiPdxSdk\Model\SecureMessageSendRequest|null $secure_message_send_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postSecureMessageSend'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function postSecureMessageSendRequest($connection_token, $uid, $con_id, $secure_message_send_request = null, string $contentType = self::contentTypes['postSecureMessageSend'][0])
    {

        // verify the required parameter 'connection_token' is set
        if ($connection_token === null || (is_array($connection_token) && count($connection_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $connection_token when calling postSecureMessageSend'
            );
        }

        // verify the required parameter 'uid' is set
        if ($uid === null || (is_array($uid) && count($uid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $uid when calling postSecureMessageSend'
            );
        }

        // verify the required parameter 'con_id' is set
        if ($con_id === null || (is_array($con_id) && count($con_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $con_id when calling postSecureMessageSend'
            );
        }



        $resourcePath = '/secure-messages/send';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $uid,
            'uid', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $con_id,
            'con_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);

        // header params
        if ($connection_token !== null) {
            $headerParams['Connection-Token'] = ObjectSerializer::toHeaderValue($connection_token);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($secure_message_send_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($secure_message_send_request));
            } else {
                $httpBody = $secure_message_send_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
