<?php
/**
 * TimelineApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Mydex\ApiPdxSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PDX API
 *
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Mydex\ApiPdxSdk\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Mydex\ApiPdxSdk\ApiException;
use Mydex\ApiPdxSdk\Configuration;
use Mydex\ApiPdxSdk\FormDataProcessor;
use Mydex\ApiPdxSdk\HeaderSelector;
use Mydex\ApiPdxSdk\ObjectSerializer;

/**
 * TimelineApi Class Doc Comment
 *
 * @category Class
 * @package  Mydex\ApiPdxSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TimelineApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getTimeline' => [
            'application/json',
        ],
        'getTimelineItem' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getTimeline
     *
     * Retrieve list of timeline items.
     *
     * @param  string $connection_token Member&#39;s Connection Key (required)
     * @param  string $uid The unique ID of a mydex member (required)
     * @param  string $con_id The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTimeline'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiPdxSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Mydex\ApiPdxSdk\Model\TimelineResponse|\Mydex\ApiPdxSdk\Model\AuthErrorResponse
     */
    public function getTimeline($connection_token, $uid, $con_id, string $contentType = self::contentTypes['getTimeline'][0])
    {
        list($response) = $this->getTimelineWithHttpInfo($connection_token, $uid, $con_id, $contentType);
        return $response;
    }

    /**
     * Operation getTimelineWithHttpInfo
     *
     * Retrieve list of timeline items.
     *
     * @param  string $connection_token Member&#39;s Connection Key (required)
     * @param  string $uid The unique ID of a mydex member (required)
     * @param  string $con_id The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTimeline'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiPdxSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Mydex\ApiPdxSdk\Model\TimelineResponse|\Mydex\ApiPdxSdk\Model\AuthErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getTimelineWithHttpInfo($connection_token, $uid, $con_id, string $contentType = self::contentTypes['getTimeline'][0])
    {
        $request = $this->getTimelineRequest($connection_token, $uid, $con_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiPdxSdk\Model\TimelineResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiPdxSdk\Model\AuthErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Mydex\ApiPdxSdk\Model\TimelineResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiPdxSdk\Model\TimelineResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiPdxSdk\Model\AuthErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getTimelineAsync
     *
     * Retrieve list of timeline items.
     *
     * @param  string $connection_token Member&#39;s Connection Key (required)
     * @param  string $uid The unique ID of a mydex member (required)
     * @param  string $con_id The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTimeline'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTimelineAsync($connection_token, $uid, $con_id, string $contentType = self::contentTypes['getTimeline'][0])
    {
        return $this->getTimelineAsyncWithHttpInfo($connection_token, $uid, $con_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getTimelineAsyncWithHttpInfo
     *
     * Retrieve list of timeline items.
     *
     * @param  string $connection_token Member&#39;s Connection Key (required)
     * @param  string $uid The unique ID of a mydex member (required)
     * @param  string $con_id The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTimeline'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTimelineAsyncWithHttpInfo($connection_token, $uid, $con_id, string $contentType = self::contentTypes['getTimeline'][0])
    {
        $returnType = '\Mydex\ApiPdxSdk\Model\TimelineResponse';
        $request = $this->getTimelineRequest($connection_token, $uid, $con_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getTimeline'
     *
     * @param  string $connection_token Member&#39;s Connection Key (required)
     * @param  string $uid The unique ID of a mydex member (required)
     * @param  string $con_id The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTimeline'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getTimelineRequest($connection_token, $uid, $con_id, string $contentType = self::contentTypes['getTimeline'][0])
    {

        // verify the required parameter 'connection_token' is set
        if ($connection_token === null || (is_array($connection_token) && count($connection_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $connection_token when calling getTimeline'
            );
        }

        // verify the required parameter 'uid' is set
        if ($uid === null || (is_array($uid) && count($uid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $uid when calling getTimeline'
            );
        }

        // verify the required parameter 'con_id' is set
        if ($con_id === null || (is_array($con_id) && count($con_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $con_id when calling getTimeline'
            );
        }


        $resourcePath = '/timeline';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $uid,
            'uid', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $con_id,
            'con_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);

        // header params
        if ($connection_token !== null) {
            $headerParams['Connection-Token'] = ObjectSerializer::toHeaderValue($connection_token);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getTimelineItem
     *
     * Retrieve a single timeline item.
     *
     * @param  string $connection_token Member&#39;s Connection Key (required)
     * @param  string $uid The unique ID of a mydex member (required)
     * @param  string $con_id The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. (required)
     * @param  string $feature_block The feature block the teimline item belongs to (required)
     * @param  int $feature_block_id The specific ID of the record within the specified feature block e.g. if &#39;referrals&#39; is the feature block, then this should be a specific referral id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTimelineItem'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiPdxSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Mydex\ApiPdxSdk\Model\TimelineSingleItemResponse|\Mydex\ApiPdxSdk\Model\AuthErrorResponse
     */
    public function getTimelineItem($connection_token, $uid, $con_id, $feature_block, $feature_block_id, string $contentType = self::contentTypes['getTimelineItem'][0])
    {
        list($response) = $this->getTimelineItemWithHttpInfo($connection_token, $uid, $con_id, $feature_block, $feature_block_id, $contentType);
        return $response;
    }

    /**
     * Operation getTimelineItemWithHttpInfo
     *
     * Retrieve a single timeline item.
     *
     * @param  string $connection_token Member&#39;s Connection Key (required)
     * @param  string $uid The unique ID of a mydex member (required)
     * @param  string $con_id The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. (required)
     * @param  string $feature_block The feature block the teimline item belongs to (required)
     * @param  int $feature_block_id The specific ID of the record within the specified feature block e.g. if &#39;referrals&#39; is the feature block, then this should be a specific referral id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTimelineItem'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiPdxSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Mydex\ApiPdxSdk\Model\TimelineSingleItemResponse|\Mydex\ApiPdxSdk\Model\AuthErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getTimelineItemWithHttpInfo($connection_token, $uid, $con_id, $feature_block, $feature_block_id, string $contentType = self::contentTypes['getTimelineItem'][0])
    {
        $request = $this->getTimelineItemRequest($connection_token, $uid, $con_id, $feature_block, $feature_block_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiPdxSdk\Model\TimelineSingleItemResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiPdxSdk\Model\AuthErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Mydex\ApiPdxSdk\Model\TimelineSingleItemResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiPdxSdk\Model\TimelineSingleItemResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiPdxSdk\Model\AuthErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getTimelineItemAsync
     *
     * Retrieve a single timeline item.
     *
     * @param  string $connection_token Member&#39;s Connection Key (required)
     * @param  string $uid The unique ID of a mydex member (required)
     * @param  string $con_id The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. (required)
     * @param  string $feature_block The feature block the teimline item belongs to (required)
     * @param  int $feature_block_id The specific ID of the record within the specified feature block e.g. if &#39;referrals&#39; is the feature block, then this should be a specific referral id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTimelineItem'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTimelineItemAsync($connection_token, $uid, $con_id, $feature_block, $feature_block_id, string $contentType = self::contentTypes['getTimelineItem'][0])
    {
        return $this->getTimelineItemAsyncWithHttpInfo($connection_token, $uid, $con_id, $feature_block, $feature_block_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getTimelineItemAsyncWithHttpInfo
     *
     * Retrieve a single timeline item.
     *
     * @param  string $connection_token Member&#39;s Connection Key (required)
     * @param  string $uid The unique ID of a mydex member (required)
     * @param  string $con_id The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. (required)
     * @param  string $feature_block The feature block the teimline item belongs to (required)
     * @param  int $feature_block_id The specific ID of the record within the specified feature block e.g. if &#39;referrals&#39; is the feature block, then this should be a specific referral id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTimelineItem'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTimelineItemAsyncWithHttpInfo($connection_token, $uid, $con_id, $feature_block, $feature_block_id, string $contentType = self::contentTypes['getTimelineItem'][0])
    {
        $returnType = '\Mydex\ApiPdxSdk\Model\TimelineSingleItemResponse';
        $request = $this->getTimelineItemRequest($connection_token, $uid, $con_id, $feature_block, $feature_block_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getTimelineItem'
     *
     * @param  string $connection_token Member&#39;s Connection Key (required)
     * @param  string $uid The unique ID of a mydex member (required)
     * @param  string $con_id The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. (required)
     * @param  string $feature_block The feature block the teimline item belongs to (required)
     * @param  int $feature_block_id The specific ID of the record within the specified feature block e.g. if &#39;referrals&#39; is the feature block, then this should be a specific referral id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTimelineItem'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getTimelineItemRequest($connection_token, $uid, $con_id, $feature_block, $feature_block_id, string $contentType = self::contentTypes['getTimelineItem'][0])
    {

        // verify the required parameter 'connection_token' is set
        if ($connection_token === null || (is_array($connection_token) && count($connection_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $connection_token when calling getTimelineItem'
            );
        }

        // verify the required parameter 'uid' is set
        if ($uid === null || (is_array($uid) && count($uid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $uid when calling getTimelineItem'
            );
        }

        // verify the required parameter 'con_id' is set
        if ($con_id === null || (is_array($con_id) && count($con_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $con_id when calling getTimelineItem'
            );
        }

        // verify the required parameter 'feature_block' is set
        if ($feature_block === null || (is_array($feature_block) && count($feature_block) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $feature_block when calling getTimelineItem'
            );
        }

        // verify the required parameter 'feature_block_id' is set
        if ($feature_block_id === null || (is_array($feature_block_id) && count($feature_block_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $feature_block_id when calling getTimelineItem'
            );
        }


        $resourcePath = '/timeline/single-item';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $uid,
            'uid', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $con_id,
            'con_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $feature_block,
            'feature_block', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $feature_block_id,
            'feature_block_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);

        // header params
        if ($connection_token !== null) {
            $headerParams['Connection-Token'] = ObjectSerializer::toHeaderValue($connection_token);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
