<?php
/**
 * ReferralCommonRequestBodyFields
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Mydex\ApiPdxSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PDX API
 *
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Mydex\ApiPdxSdk\Model;

use \ArrayAccess;
use \Mydex\ApiPdxSdk\ObjectSerializer;

/**
 * ReferralCommonRequestBodyFields Class Doc Comment
 *
 * @category Class
 * @description Common fields shared across all referral types
 * @package  Mydex\ApiPdxSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ReferralCommonRequestBodyFields implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ReferralCommonRequestBodyFields';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'service_id' => 'int',
        'referree_background' => 'string',
        'referree_requirements' => 'string',
        'referree_availability' => '\Mydex\ApiPdxSdk\Model\ReferralCommonRequestBodyFieldsReferreeAvailability',
        'referrer_name' => 'string',
        'service_name' => 'string',
        'service_description' => 'string',
        'service_url' => 'string',
        'service_email' => 'string',
        'contact_number' => 'string',
        'memo' => 'string',
        'start_time' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'service_id' => null,
        'referree_background' => null,
        'referree_requirements' => null,
        'referree_availability' => null,
        'referrer_name' => null,
        'service_name' => null,
        'service_description' => null,
        'service_url' => 'uri',
        'service_email' => 'email',
        'contact_number' => null,
        'memo' => null,
        'start_time' => 'int64'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'service_id' => false,
        'referree_background' => false,
        'referree_requirements' => false,
        'referree_availability' => false,
        'referrer_name' => false,
        'service_name' => false,
        'service_description' => false,
        'service_url' => false,
        'service_email' => false,
        'contact_number' => false,
        'memo' => false,
        'start_time' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'service_id' => 'service_id',
        'referree_background' => 'referree_background',
        'referree_requirements' => 'referree_requirements',
        'referree_availability' => 'referree_availability',
        'referrer_name' => 'referrer_name',
        'service_name' => 'service_name',
        'service_description' => 'service_description',
        'service_url' => 'service_url',
        'service_email' => 'service_email',
        'contact_number' => 'contact_number',
        'memo' => 'memo',
        'start_time' => 'start_time'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'service_id' => 'setServiceId',
        'referree_background' => 'setReferreeBackground',
        'referree_requirements' => 'setReferreeRequirements',
        'referree_availability' => 'setReferreeAvailability',
        'referrer_name' => 'setReferrerName',
        'service_name' => 'setServiceName',
        'service_description' => 'setServiceDescription',
        'service_url' => 'setServiceUrl',
        'service_email' => 'setServiceEmail',
        'contact_number' => 'setContactNumber',
        'memo' => 'setMemo',
        'start_time' => 'setStartTime'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'service_id' => 'getServiceId',
        'referree_background' => 'getReferreeBackground',
        'referree_requirements' => 'getReferreeRequirements',
        'referree_availability' => 'getReferreeAvailability',
        'referrer_name' => 'getReferrerName',
        'service_name' => 'getServiceName',
        'service_description' => 'getServiceDescription',
        'service_url' => 'getServiceUrl',
        'service_email' => 'getServiceEmail',
        'contact_number' => 'getContactNumber',
        'memo' => 'getMemo',
        'start_time' => 'getStartTime'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('service_id', $data ?? [], null);
        $this->setIfExists('referree_background', $data ?? [], null);
        $this->setIfExists('referree_requirements', $data ?? [], null);
        $this->setIfExists('referree_availability', $data ?? [], null);
        $this->setIfExists('referrer_name', $data ?? [], null);
        $this->setIfExists('service_name', $data ?? [], null);
        $this->setIfExists('service_description', $data ?? [], null);
        $this->setIfExists('service_url', $data ?? [], null);
        $this->setIfExists('service_email', $data ?? [], null);
        $this->setIfExists('contact_number', $data ?? [], null);
        $this->setIfExists('memo', $data ?? [], null);
        $this->setIfExists('start_time', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets service_id
     *
     * @return int|null
     */
    public function getServiceId()
    {
        return $this->container['service_id'];
    }

    /**
     * Sets service_id
     *
     * @param int|null $service_id ID of the service being referred to
     *
     * @return self
     */
    public function setServiceId($service_id)
    {
        if (is_null($service_id)) {
            throw new \InvalidArgumentException('non-nullable service_id cannot be null');
        }
        $this->container['service_id'] = $service_id;

        return $this;
    }

    /**
     * Gets referree_background
     *
     * @return string|null
     */
    public function getReferreeBackground()
    {
        return $this->container['referree_background'];
    }

    /**
     * Sets referree_background
     *
     * @param string|null $referree_background Background information about the referree
     *
     * @return self
     */
    public function setReferreeBackground($referree_background)
    {
        if (is_null($referree_background)) {
            throw new \InvalidArgumentException('non-nullable referree_background cannot be null');
        }
        $this->container['referree_background'] = $referree_background;

        return $this;
    }

    /**
     * Gets referree_requirements
     *
     * @return string|null
     */
    public function getReferreeRequirements()
    {
        return $this->container['referree_requirements'];
    }

    /**
     * Sets referree_requirements
     *
     * @param string|null $referree_requirements Requirements of the referree
     *
     * @return self
     */
    public function setReferreeRequirements($referree_requirements)
    {
        if (is_null($referree_requirements)) {
            throw new \InvalidArgumentException('non-nullable referree_requirements cannot be null');
        }
        $this->container['referree_requirements'] = $referree_requirements;

        return $this;
    }

    /**
     * Gets referree_availability
     *
     * @return \Mydex\ApiPdxSdk\Model\ReferralCommonRequestBodyFieldsReferreeAvailability|null
     */
    public function getReferreeAvailability()
    {
        return $this->container['referree_availability'];
    }

    /**
     * Sets referree_availability
     *
     * @param \Mydex\ApiPdxSdk\Model\ReferralCommonRequestBodyFieldsReferreeAvailability|null $referree_availability referree_availability
     *
     * @return self
     */
    public function setReferreeAvailability($referree_availability)
    {
        if (is_null($referree_availability)) {
            throw new \InvalidArgumentException('non-nullable referree_availability cannot be null');
        }
        $this->container['referree_availability'] = $referree_availability;

        return $this;
    }

    /**
     * Gets referrer_name
     *
     * @return string|null
     */
    public function getReferrerName()
    {
        return $this->container['referrer_name'];
    }

    /**
     * Sets referrer_name
     *
     * @param string|null $referrer_name Name of the person making the referral
     *
     * @return self
     */
    public function setReferrerName($referrer_name)
    {
        if (is_null($referrer_name)) {
            throw new \InvalidArgumentException('non-nullable referrer_name cannot be null');
        }
        $this->container['referrer_name'] = $referrer_name;

        return $this;
    }

    /**
     * Gets service_name
     *
     * @return string|null
     */
    public function getServiceName()
    {
        return $this->container['service_name'];
    }

    /**
     * Sets service_name
     *
     * @param string|null $service_name Name of the service
     *
     * @return self
     */
    public function setServiceName($service_name)
    {
        if (is_null($service_name)) {
            throw new \InvalidArgumentException('non-nullable service_name cannot be null');
        }
        $this->container['service_name'] = $service_name;

        return $this;
    }

    /**
     * Gets service_description
     *
     * @return string|null
     */
    public function getServiceDescription()
    {
        return $this->container['service_description'];
    }

    /**
     * Sets service_description
     *
     * @param string|null $service_description Description of the service
     *
     * @return self
     */
    public function setServiceDescription($service_description)
    {
        if (is_null($service_description)) {
            throw new \InvalidArgumentException('non-nullable service_description cannot be null');
        }
        $this->container['service_description'] = $service_description;

        return $this;
    }

    /**
     * Gets service_url
     *
     * @return string|null
     */
    public function getServiceUrl()
    {
        return $this->container['service_url'];
    }

    /**
     * Sets service_url
     *
     * @param string|null $service_url URL of the service
     *
     * @return self
     */
    public function setServiceUrl($service_url)
    {
        if (is_null($service_url)) {
            throw new \InvalidArgumentException('non-nullable service_url cannot be null');
        }
        $this->container['service_url'] = $service_url;

        return $this;
    }

    /**
     * Gets service_email
     *
     * @return string|null
     */
    public function getServiceEmail()
    {
        return $this->container['service_email'];
    }

    /**
     * Sets service_email
     *
     * @param string|null $service_email Email address of the service
     *
     * @return self
     */
    public function setServiceEmail($service_email)
    {
        if (is_null($service_email)) {
            throw new \InvalidArgumentException('non-nullable service_email cannot be null');
        }
        $this->container['service_email'] = $service_email;

        return $this;
    }

    /**
     * Gets contact_number
     *
     * @return string|null
     */
    public function getContactNumber()
    {
        return $this->container['contact_number'];
    }

    /**
     * Sets contact_number
     *
     * @param string|null $contact_number Contact number for the service
     *
     * @return self
     */
    public function setContactNumber($contact_number)
    {
        if (is_null($contact_number)) {
            throw new \InvalidArgumentException('non-nullable contact_number cannot be null');
        }
        $this->container['contact_number'] = $contact_number;

        return $this;
    }

    /**
     * Gets memo
     *
     * @return string|null
     */
    public function getMemo()
    {
        return $this->container['memo'];
    }

    /**
     * Sets memo
     *
     * @param string|null $memo Internal memo or notes
     *
     * @return self
     */
    public function setMemo($memo)
    {
        if (is_null($memo)) {
            throw new \InvalidArgumentException('non-nullable memo cannot be null');
        }
        $this->container['memo'] = $memo;

        return $this;
    }

    /**
     * Gets start_time
     *
     * @return int|null
     */
    public function getStartTime()
    {
        return $this->container['start_time'];
    }

    /**
     * Sets start_time
     *
     * @param int|null $start_time Start time as a Unix timestamp
     *
     * @return self
     */
    public function setStartTime($start_time)
    {
        if (is_null($start_time)) {
            throw new \InvalidArgumentException('non-nullable start_time cannot be null');
        }
        $this->container['start_time'] = $start_time;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


