<?php
/**
 * TimelineSingleItemResponseTimelineItem
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Mydex\ApiPdxSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PDX API
 *
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Mydex\ApiPdxSdk\Model;

use \ArrayAccess;
use \Mydex\ApiPdxSdk\ObjectSerializer;

/**
 * TimelineSingleItemResponseTimelineItem Class Doc Comment
 *
 * @category Class
 * @description The timeline item, which can be one of multiple types, returned as an object
 * @package  Mydex\ApiPdxSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TimelineSingleItemResponseTimelineItem implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'TimelineSingleItemResponse_timeline_item';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'feature_block' => 'string',
        'feature_block_id' => 'int',
        'instance' => 'string',
        'source' => 'string',
        'created_timestamp' => 'string',
        'updated_timestamp' => 'string',
        'service_id' => 'int',
        'service_name' => 'string',
        'service_description' => 'string',
        'service_url' => 'string',
        'service_email' => 'string',
        'contact_name' => 'string',
        'contact_title' => 'string',
        'contact_number' => 'string',
        'referrer_name' => 'string',
        'status' => 'string',
        'external_id' => 'string',
        'start_time' => 'int',
        'end_time' => 'int',
        'is_processed' => 'bool',
        'complete_time' => 'int',
        'memo' => 'string',
        'duration' => 'string',
        'referree_background' => 'string',
        'referree_requirements' => 'string',
        'referree_availability' => 'object',
        'type' => 'string',
        'start_timestamp' => 'string',
        'item_timestamp' => 'int',
        'conversation_id' => 'string',
        'time_sent' => 'string',
        'time_received' => 'string',
        'message_from' => 'string',
        'message_to' => 'string',
        'message_content' => 'string',
        'external_uid' => 'string',
        'title' => 'string',
        'description' => 'string',
        'end_timestamp' => 'string',
        'organiser' => 'string',
        'attendee' => 'string',
        'location' => 'string',
        'tags' => 'string',
        'trigger' => 'string',
        'action' => 'string',
        'reminder_description' => 'string',
        'duration_string' => 'string',
        'duration_of_event' => 'float'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'feature_block' => null,
        'feature_block_id' => null,
        'instance' => null,
        'source' => null,
        'created_timestamp' => null,
        'updated_timestamp' => null,
        'service_id' => null,
        'service_name' => null,
        'service_description' => null,
        'service_url' => null,
        'service_email' => null,
        'contact_name' => null,
        'contact_title' => null,
        'contact_number' => null,
        'referrer_name' => null,
        'status' => null,
        'external_id' => null,
        'start_time' => 'int64',
        'end_time' => 'int64',
        'is_processed' => null,
        'complete_time' => null,
        'memo' => null,
        'duration' => null,
        'referree_background' => null,
        'referree_requirements' => null,
        'referree_availability' => null,
        'type' => null,
        'start_timestamp' => null,
        'item_timestamp' => 'int64',
        'conversation_id' => null,
        'time_sent' => null,
        'time_received' => null,
        'message_from' => null,
        'message_to' => null,
        'message_content' => null,
        'external_uid' => null,
        'title' => null,
        'description' => null,
        'end_timestamp' => null,
        'organiser' => null,
        'attendee' => null,
        'location' => null,
        'tags' => null,
        'trigger' => null,
        'action' => null,
        'reminder_description' => null,
        'duration_string' => null,
        'duration_of_event' => 'float'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'feature_block' => false,
        'feature_block_id' => false,
        'instance' => false,
        'source' => false,
        'created_timestamp' => false,
        'updated_timestamp' => false,
        'service_id' => false,
        'service_name' => false,
        'service_description' => false,
        'service_url' => false,
        'service_email' => false,
        'contact_name' => false,
        'contact_title' => false,
        'contact_number' => false,
        'referrer_name' => false,
        'status' => true,
        'external_id' => false,
        'start_time' => false,
        'end_time' => false,
        'is_processed' => false,
        'complete_time' => false,
        'memo' => false,
        'duration' => false,
        'referree_background' => false,
        'referree_requirements' => false,
        'referree_availability' => false,
        'type' => true,
        'start_timestamp' => false,
        'item_timestamp' => false,
        'conversation_id' => false,
        'time_sent' => false,
        'time_received' => false,
        'message_from' => false,
        'message_to' => false,
        'message_content' => false,
        'external_uid' => true,
        'title' => true,
        'description' => true,
        'end_timestamp' => false,
        'organiser' => true,
        'attendee' => true,
        'location' => true,
        'tags' => true,
        'trigger' => true,
        'action' => true,
        'reminder_description' => true,
        'duration_string' => false,
        'duration_of_event' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'feature_block' => 'feature_block',
        'feature_block_id' => 'feature_block_id',
        'instance' => 'instance',
        'source' => 'source',
        'created_timestamp' => 'created_timestamp',
        'updated_timestamp' => 'updated_timestamp',
        'service_id' => 'service_id',
        'service_name' => 'service_name',
        'service_description' => 'service_description',
        'service_url' => 'service_url',
        'service_email' => 'service_email',
        'contact_name' => 'contact_name',
        'contact_title' => 'contact_title',
        'contact_number' => 'contact_number',
        'referrer_name' => 'referrer_name',
        'status' => 'status',
        'external_id' => 'external_id',
        'start_time' => 'start_time',
        'end_time' => 'end_time',
        'is_processed' => 'is_processed',
        'complete_time' => 'complete_time',
        'memo' => 'memo',
        'duration' => 'duration',
        'referree_background' => 'referree_background',
        'referree_requirements' => 'referree_requirements',
        'referree_availability' => 'referree_availability',
        'type' => 'type',
        'start_timestamp' => 'start_timestamp',
        'item_timestamp' => 'item_timestamp',
        'conversation_id' => 'conversation_id',
        'time_sent' => 'time_sent',
        'time_received' => 'time_received',
        'message_from' => 'message_from',
        'message_to' => 'message_to',
        'message_content' => 'message_content',
        'external_uid' => 'external_uid',
        'title' => 'title',
        'description' => 'description',
        'end_timestamp' => 'end_timestamp',
        'organiser' => 'organiser',
        'attendee' => 'attendee',
        'location' => 'location',
        'tags' => 'tags',
        'trigger' => 'trigger',
        'action' => 'action',
        'reminder_description' => 'reminder_description',
        'duration_string' => 'duration_string',
        'duration_of_event' => 'duration_of_event'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'feature_block' => 'setFeatureBlock',
        'feature_block_id' => 'setFeatureBlockId',
        'instance' => 'setInstance',
        'source' => 'setSource',
        'created_timestamp' => 'setCreatedTimestamp',
        'updated_timestamp' => 'setUpdatedTimestamp',
        'service_id' => 'setServiceId',
        'service_name' => 'setServiceName',
        'service_description' => 'setServiceDescription',
        'service_url' => 'setServiceUrl',
        'service_email' => 'setServiceEmail',
        'contact_name' => 'setContactName',
        'contact_title' => 'setContactTitle',
        'contact_number' => 'setContactNumber',
        'referrer_name' => 'setReferrerName',
        'status' => 'setStatus',
        'external_id' => 'setExternalId',
        'start_time' => 'setStartTime',
        'end_time' => 'setEndTime',
        'is_processed' => 'setIsProcessed',
        'complete_time' => 'setCompleteTime',
        'memo' => 'setMemo',
        'duration' => 'setDuration',
        'referree_background' => 'setReferreeBackground',
        'referree_requirements' => 'setReferreeRequirements',
        'referree_availability' => 'setReferreeAvailability',
        'type' => 'setType',
        'start_timestamp' => 'setStartTimestamp',
        'item_timestamp' => 'setItemTimestamp',
        'conversation_id' => 'setConversationId',
        'time_sent' => 'setTimeSent',
        'time_received' => 'setTimeReceived',
        'message_from' => 'setMessageFrom',
        'message_to' => 'setMessageTo',
        'message_content' => 'setMessageContent',
        'external_uid' => 'setExternalUid',
        'title' => 'setTitle',
        'description' => 'setDescription',
        'end_timestamp' => 'setEndTimestamp',
        'organiser' => 'setOrganiser',
        'attendee' => 'setAttendee',
        'location' => 'setLocation',
        'tags' => 'setTags',
        'trigger' => 'setTrigger',
        'action' => 'setAction',
        'reminder_description' => 'setReminderDescription',
        'duration_string' => 'setDurationString',
        'duration_of_event' => 'setDurationOfEvent'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'feature_block' => 'getFeatureBlock',
        'feature_block_id' => 'getFeatureBlockId',
        'instance' => 'getInstance',
        'source' => 'getSource',
        'created_timestamp' => 'getCreatedTimestamp',
        'updated_timestamp' => 'getUpdatedTimestamp',
        'service_id' => 'getServiceId',
        'service_name' => 'getServiceName',
        'service_description' => 'getServiceDescription',
        'service_url' => 'getServiceUrl',
        'service_email' => 'getServiceEmail',
        'contact_name' => 'getContactName',
        'contact_title' => 'getContactTitle',
        'contact_number' => 'getContactNumber',
        'referrer_name' => 'getReferrerName',
        'status' => 'getStatus',
        'external_id' => 'getExternalId',
        'start_time' => 'getStartTime',
        'end_time' => 'getEndTime',
        'is_processed' => 'getIsProcessed',
        'complete_time' => 'getCompleteTime',
        'memo' => 'getMemo',
        'duration' => 'getDuration',
        'referree_background' => 'getReferreeBackground',
        'referree_requirements' => 'getReferreeRequirements',
        'referree_availability' => 'getReferreeAvailability',
        'type' => 'getType',
        'start_timestamp' => 'getStartTimestamp',
        'item_timestamp' => 'getItemTimestamp',
        'conversation_id' => 'getConversationId',
        'time_sent' => 'getTimeSent',
        'time_received' => 'getTimeReceived',
        'message_from' => 'getMessageFrom',
        'message_to' => 'getMessageTo',
        'message_content' => 'getMessageContent',
        'external_uid' => 'getExternalUid',
        'title' => 'getTitle',
        'description' => 'getDescription',
        'end_timestamp' => 'getEndTimestamp',
        'organiser' => 'getOrganiser',
        'attendee' => 'getAttendee',
        'location' => 'getLocation',
        'tags' => 'getTags',
        'trigger' => 'getTrigger',
        'action' => 'getAction',
        'reminder_description' => 'getReminderDescription',
        'duration_string' => 'getDurationString',
        'duration_of_event' => 'getDurationOfEvent'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('feature_block', $data ?? [], null);
        $this->setIfExists('feature_block_id', $data ?? [], null);
        $this->setIfExists('instance', $data ?? [], null);
        $this->setIfExists('source', $data ?? [], null);
        $this->setIfExists('created_timestamp', $data ?? [], null);
        $this->setIfExists('updated_timestamp', $data ?? [], null);
        $this->setIfExists('service_id', $data ?? [], null);
        $this->setIfExists('service_name', $data ?? [], null);
        $this->setIfExists('service_description', $data ?? [], null);
        $this->setIfExists('service_url', $data ?? [], null);
        $this->setIfExists('service_email', $data ?? [], null);
        $this->setIfExists('contact_name', $data ?? [], null);
        $this->setIfExists('contact_title', $data ?? [], null);
        $this->setIfExists('contact_number', $data ?? [], null);
        $this->setIfExists('referrer_name', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('external_id', $data ?? [], null);
        $this->setIfExists('start_time', $data ?? [], null);
        $this->setIfExists('end_time', $data ?? [], null);
        $this->setIfExists('is_processed', $data ?? [], null);
        $this->setIfExists('complete_time', $data ?? [], null);
        $this->setIfExists('memo', $data ?? [], null);
        $this->setIfExists('duration', $data ?? [], null);
        $this->setIfExists('referree_background', $data ?? [], null);
        $this->setIfExists('referree_requirements', $data ?? [], null);
        $this->setIfExists('referree_availability', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('start_timestamp', $data ?? [], null);
        $this->setIfExists('item_timestamp', $data ?? [], null);
        $this->setIfExists('conversation_id', $data ?? [], null);
        $this->setIfExists('time_sent', $data ?? [], null);
        $this->setIfExists('time_received', $data ?? [], null);
        $this->setIfExists('message_from', $data ?? [], null);
        $this->setIfExists('message_to', $data ?? [], null);
        $this->setIfExists('message_content', $data ?? [], null);
        $this->setIfExists('external_uid', $data ?? [], null);
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('end_timestamp', $data ?? [], null);
        $this->setIfExists('organiser', $data ?? [], null);
        $this->setIfExists('attendee', $data ?? [], null);
        $this->setIfExists('location', $data ?? [], null);
        $this->setIfExists('tags', $data ?? [], null);
        $this->setIfExists('trigger', $data ?? [], null);
        $this->setIfExists('action', $data ?? [], null);
        $this->setIfExists('reminder_description', $data ?? [], null);
        $this->setIfExists('duration_string', $data ?? [], null);
        $this->setIfExists('duration_of_event', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets feature_block
     *
     * @return string|null
     */
    public function getFeatureBlock()
    {
        return $this->container['feature_block'];
    }

    /**
     * Sets feature_block
     *
     * @param string|null $feature_block Type of feature block this timeline item belongs to
     *
     * @return self
     */
    public function setFeatureBlock($feature_block)
    {
        if (is_null($feature_block)) {
            throw new \InvalidArgumentException('non-nullable feature_block cannot be null');
        }
        $this->container['feature_block'] = $feature_block;

        return $this;
    }

    /**
     * Gets feature_block_id
     *
     * @return int|null
     */
    public function getFeatureBlockId()
    {
        return $this->container['feature_block_id'];
    }

    /**
     * Sets feature_block_id
     *
     * @param int|null $feature_block_id ID of the feature block
     *
     * @return self
     */
    public function setFeatureBlockId($feature_block_id)
    {
        if (is_null($feature_block_id)) {
            throw new \InvalidArgumentException('non-nullable feature_block_id cannot be null');
        }
        $this->container['feature_block_id'] = $feature_block_id;

        return $this;
    }

    /**
     * Gets instance
     *
     * @return string|null
     */
    public function getInstance()
    {
        return $this->container['instance'];
    }

    /**
     * Sets instance
     *
     * @param string|null $instance instance
     *
     * @return self
     */
    public function setInstance($instance)
    {
        if (is_null($instance)) {
            throw new \InvalidArgumentException('non-nullable instance cannot be null');
        }
        $this->container['instance'] = $instance;

        return $this;
    }

    /**
     * Gets source
     *
     * @return string|null
     */
    public function getSource()
    {
        return $this->container['source'];
    }

    /**
     * Sets source
     *
     * @param string|null $source source
     *
     * @return self
     */
    public function setSource($source)
    {
        if (is_null($source)) {
            throw new \InvalidArgumentException('non-nullable source cannot be null');
        }
        $this->container['source'] = $source;

        return $this;
    }

    /**
     * Gets created_timestamp
     *
     * @return string|null
     */
    public function getCreatedTimestamp()
    {
        return $this->container['created_timestamp'];
    }

    /**
     * Sets created_timestamp
     *
     * @param string|null $created_timestamp created_timestamp
     *
     * @return self
     */
    public function setCreatedTimestamp($created_timestamp)
    {
        if (is_null($created_timestamp)) {
            throw new \InvalidArgumentException('non-nullable created_timestamp cannot be null');
        }
        $this->container['created_timestamp'] = $created_timestamp;

        return $this;
    }

    /**
     * Gets updated_timestamp
     *
     * @return string|null
     */
    public function getUpdatedTimestamp()
    {
        return $this->container['updated_timestamp'];
    }

    /**
     * Sets updated_timestamp
     *
     * @param string|null $updated_timestamp updated_timestamp
     *
     * @return self
     */
    public function setUpdatedTimestamp($updated_timestamp)
    {
        if (is_null($updated_timestamp)) {
            throw new \InvalidArgumentException('non-nullable updated_timestamp cannot be null');
        }
        $this->container['updated_timestamp'] = $updated_timestamp;

        return $this;
    }

    /**
     * Gets service_id
     *
     * @return int|null
     */
    public function getServiceId()
    {
        return $this->container['service_id'];
    }

    /**
     * Sets service_id
     *
     * @param int|null $service_id The id of the service that the referral relates to
     *
     * @return self
     */
    public function setServiceId($service_id)
    {
        if (is_null($service_id)) {
            throw new \InvalidArgumentException('non-nullable service_id cannot be null');
        }
        $this->container['service_id'] = $service_id;

        return $this;
    }

    /**
     * Gets service_name
     *
     * @return string|null
     */
    public function getServiceName()
    {
        return $this->container['service_name'];
    }

    /**
     * Sets service_name
     *
     * @param string|null $service_name service_name
     *
     * @return self
     */
    public function setServiceName($service_name)
    {
        if (is_null($service_name)) {
            throw new \InvalidArgumentException('non-nullable service_name cannot be null');
        }
        $this->container['service_name'] = $service_name;

        return $this;
    }

    /**
     * Gets service_description
     *
     * @return string|null
     */
    public function getServiceDescription()
    {
        return $this->container['service_description'];
    }

    /**
     * Sets service_description
     *
     * @param string|null $service_description service_description
     *
     * @return self
     */
    public function setServiceDescription($service_description)
    {
        if (is_null($service_description)) {
            throw new \InvalidArgumentException('non-nullable service_description cannot be null');
        }
        $this->container['service_description'] = $service_description;

        return $this;
    }

    /**
     * Gets service_url
     *
     * @return string|null
     */
    public function getServiceUrl()
    {
        return $this->container['service_url'];
    }

    /**
     * Sets service_url
     *
     * @param string|null $service_url service_url
     *
     * @return self
     */
    public function setServiceUrl($service_url)
    {
        if (is_null($service_url)) {
            throw new \InvalidArgumentException('non-nullable service_url cannot be null');
        }
        $this->container['service_url'] = $service_url;

        return $this;
    }

    /**
     * Gets service_email
     *
     * @return string|null
     */
    public function getServiceEmail()
    {
        return $this->container['service_email'];
    }

    /**
     * Sets service_email
     *
     * @param string|null $service_email service_email
     *
     * @return self
     */
    public function setServiceEmail($service_email)
    {
        if (is_null($service_email)) {
            throw new \InvalidArgumentException('non-nullable service_email cannot be null');
        }
        $this->container['service_email'] = $service_email;

        return $this;
    }

    /**
     * Gets contact_name
     *
     * @return string|null
     */
    public function getContactName()
    {
        return $this->container['contact_name'];
    }

    /**
     * Sets contact_name
     *
     * @param string|null $contact_name contact_name
     *
     * @return self
     */
    public function setContactName($contact_name)
    {
        if (is_null($contact_name)) {
            throw new \InvalidArgumentException('non-nullable contact_name cannot be null');
        }
        $this->container['contact_name'] = $contact_name;

        return $this;
    }

    /**
     * Gets contact_title
     *
     * @return string|null
     */
    public function getContactTitle()
    {
        return $this->container['contact_title'];
    }

    /**
     * Sets contact_title
     *
     * @param string|null $contact_title contact_title
     *
     * @return self
     */
    public function setContactTitle($contact_title)
    {
        if (is_null($contact_title)) {
            throw new \InvalidArgumentException('non-nullable contact_title cannot be null');
        }
        $this->container['contact_title'] = $contact_title;

        return $this;
    }

    /**
     * Gets contact_number
     *
     * @return string|null
     */
    public function getContactNumber()
    {
        return $this->container['contact_number'];
    }

    /**
     * Sets contact_number
     *
     * @param string|null $contact_number contact_number
     *
     * @return self
     */
    public function setContactNumber($contact_number)
    {
        if (is_null($contact_number)) {
            throw new \InvalidArgumentException('non-nullable contact_number cannot be null');
        }
        $this->container['contact_number'] = $contact_number;

        return $this;
    }

    /**
     * Gets referrer_name
     *
     * @return string|null
     */
    public function getReferrerName()
    {
        return $this->container['referrer_name'];
    }

    /**
     * Sets referrer_name
     *
     * @param string|null $referrer_name referrer_name
     *
     * @return self
     */
    public function setReferrerName($referrer_name)
    {
        if (is_null($referrer_name)) {
            throw new \InvalidArgumentException('non-nullable referrer_name cannot be null');
        }
        $this->container['referrer_name'] = $referrer_name;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            array_push($this->openAPINullablesSetToNull, 'status');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('status', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets external_id
     *
     * @return string|null
     */
    public function getExternalId()
    {
        return $this->container['external_id'];
    }

    /**
     * Sets external_id
     *
     * @param string|null $external_id external_id
     *
     * @return self
     */
    public function setExternalId($external_id)
    {
        if (is_null($external_id)) {
            throw new \InvalidArgumentException('non-nullable external_id cannot be null');
        }
        $this->container['external_id'] = $external_id;

        return $this;
    }

    /**
     * Gets start_time
     *
     * @return int|null
     */
    public function getStartTime()
    {
        return $this->container['start_time'];
    }

    /**
     * Sets start_time
     *
     * @param int|null $start_time start_time
     *
     * @return self
     */
    public function setStartTime($start_time)
    {
        if (is_null($start_time)) {
            throw new \InvalidArgumentException('non-nullable start_time cannot be null');
        }
        $this->container['start_time'] = $start_time;

        return $this;
    }

    /**
     * Gets end_time
     *
     * @return int|null
     */
    public function getEndTime()
    {
        return $this->container['end_time'];
    }

    /**
     * Sets end_time
     *
     * @param int|null $end_time end_time
     *
     * @return self
     */
    public function setEndTime($end_time)
    {
        if (is_null($end_time)) {
            throw new \InvalidArgumentException('non-nullable end_time cannot be null');
        }
        $this->container['end_time'] = $end_time;

        return $this;
    }

    /**
     * Gets is_processed
     *
     * @return bool|null
     */
    public function getIsProcessed()
    {
        return $this->container['is_processed'];
    }

    /**
     * Sets is_processed
     *
     * @param bool|null $is_processed is_processed
     *
     * @return self
     */
    public function setIsProcessed($is_processed)
    {
        if (is_null($is_processed)) {
            throw new \InvalidArgumentException('non-nullable is_processed cannot be null');
        }
        $this->container['is_processed'] = $is_processed;

        return $this;
    }

    /**
     * Gets complete_time
     *
     * @return int|null
     */
    public function getCompleteTime()
    {
        return $this->container['complete_time'];
    }

    /**
     * Sets complete_time
     *
     * @param int|null $complete_time complete_time
     *
     * @return self
     */
    public function setCompleteTime($complete_time)
    {
        if (is_null($complete_time)) {
            throw new \InvalidArgumentException('non-nullable complete_time cannot be null');
        }
        $this->container['complete_time'] = $complete_time;

        return $this;
    }

    /**
     * Gets memo
     *
     * @return string|null
     */
    public function getMemo()
    {
        return $this->container['memo'];
    }

    /**
     * Sets memo
     *
     * @param string|null $memo memo
     *
     * @return self
     */
    public function setMemo($memo)
    {
        if (is_null($memo)) {
            throw new \InvalidArgumentException('non-nullable memo cannot be null');
        }
        $this->container['memo'] = $memo;

        return $this;
    }

    /**
     * Gets duration
     *
     * @return string|null
     */
    public function getDuration()
    {
        return $this->container['duration'];
    }

    /**
     * Sets duration
     *
     * @param string|null $duration duration
     *
     * @return self
     */
    public function setDuration($duration)
    {
        if (is_null($duration)) {
            throw new \InvalidArgumentException('non-nullable duration cannot be null');
        }
        $this->container['duration'] = $duration;

        return $this;
    }

    /**
     * Gets referree_background
     *
     * @return string|null
     */
    public function getReferreeBackground()
    {
        return $this->container['referree_background'];
    }

    /**
     * Sets referree_background
     *
     * @param string|null $referree_background referree_background
     *
     * @return self
     */
    public function setReferreeBackground($referree_background)
    {
        if (is_null($referree_background)) {
            throw new \InvalidArgumentException('non-nullable referree_background cannot be null');
        }
        $this->container['referree_background'] = $referree_background;

        return $this;
    }

    /**
     * Gets referree_requirements
     *
     * @return string|null
     */
    public function getReferreeRequirements()
    {
        return $this->container['referree_requirements'];
    }

    /**
     * Sets referree_requirements
     *
     * @param string|null $referree_requirements referree_requirements
     *
     * @return self
     */
    public function setReferreeRequirements($referree_requirements)
    {
        if (is_null($referree_requirements)) {
            throw new \InvalidArgumentException('non-nullable referree_requirements cannot be null');
        }
        $this->container['referree_requirements'] = $referree_requirements;

        return $this;
    }

    /**
     * Gets referree_availability
     *
     * @return object|null
     */
    public function getReferreeAvailability()
    {
        return $this->container['referree_availability'];
    }

    /**
     * Sets referree_availability
     *
     * @param object|null $referree_availability Availability of the referree in AM/PM slots
     *
     * @return self
     */
    public function setReferreeAvailability($referree_availability)
    {
        if (is_null($referree_availability)) {
            throw new \InvalidArgumentException('non-nullable referree_availability cannot be null');
        }
        $this->container['referree_availability'] = $referree_availability;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string|null $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            array_push($this->openAPINullablesSetToNull, 'type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets start_timestamp
     *
     * @return string|null
     */
    public function getStartTimestamp()
    {
        return $this->container['start_timestamp'];
    }

    /**
     * Sets start_timestamp
     *
     * @param string|null $start_timestamp start_timestamp
     *
     * @return self
     */
    public function setStartTimestamp($start_timestamp)
    {
        if (is_null($start_timestamp)) {
            throw new \InvalidArgumentException('non-nullable start_timestamp cannot be null');
        }
        $this->container['start_timestamp'] = $start_timestamp;

        return $this;
    }

    /**
     * Gets item_timestamp
     *
     * @return int|null
     */
    public function getItemTimestamp()
    {
        return $this->container['item_timestamp'];
    }

    /**
     * Sets item_timestamp
     *
     * @param int|null $item_timestamp Raw timestamp of the timeline item
     *
     * @return self
     */
    public function setItemTimestamp($item_timestamp)
    {
        if (is_null($item_timestamp)) {
            throw new \InvalidArgumentException('non-nullable item_timestamp cannot be null');
        }
        $this->container['item_timestamp'] = $item_timestamp;

        return $this;
    }

    /**
     * Gets conversation_id
     *
     * @return string|null
     */
    public function getConversationId()
    {
        return $this->container['conversation_id'];
    }

    /**
     * Sets conversation_id
     *
     * @param string|null $conversation_id Conversation identifier
     *
     * @return self
     */
    public function setConversationId($conversation_id)
    {
        if (is_null($conversation_id)) {
            throw new \InvalidArgumentException('non-nullable conversation_id cannot be null');
        }
        $this->container['conversation_id'] = $conversation_id;

        return $this;
    }

    /**
     * Gets time_sent
     *
     * @return string|null
     */
    public function getTimeSent()
    {
        return $this->container['time_sent'];
    }

    /**
     * Sets time_sent
     *
     * @param string|null $time_sent Timestamp when message was sent
     *
     * @return self
     */
    public function setTimeSent($time_sent)
    {
        if (is_null($time_sent)) {
            throw new \InvalidArgumentException('non-nullable time_sent cannot be null');
        }
        $this->container['time_sent'] = $time_sent;

        return $this;
    }

    /**
     * Gets time_received
     *
     * @return string|null
     */
    public function getTimeReceived()
    {
        return $this->container['time_received'];
    }

    /**
     * Sets time_received
     *
     * @param string|null $time_received Timestamp when message was received
     *
     * @return self
     */
    public function setTimeReceived($time_received)
    {
        if (is_null($time_received)) {
            throw new \InvalidArgumentException('non-nullable time_received cannot be null');
        }
        $this->container['time_received'] = $time_received;

        return $this;
    }

    /**
     * Gets message_from
     *
     * @return string|null
     */
    public function getMessageFrom()
    {
        return $this->container['message_from'];
    }

    /**
     * Sets message_from
     *
     * @param string|null $message_from Sender of the message (present on received messages)
     *
     * @return self
     */
    public function setMessageFrom($message_from)
    {
        if (is_null($message_from)) {
            throw new \InvalidArgumentException('non-nullable message_from cannot be null');
        }
        $this->container['message_from'] = $message_from;

        return $this;
    }

    /**
     * Gets message_to
     *
     * @return string|null
     */
    public function getMessageTo()
    {
        return $this->container['message_to'];
    }

    /**
     * Sets message_to
     *
     * @param string|null $message_to Recipient of the message (present on sent messages)
     *
     * @return self
     */
    public function setMessageTo($message_to)
    {
        if (is_null($message_to)) {
            throw new \InvalidArgumentException('non-nullable message_to cannot be null');
        }
        $this->container['message_to'] = $message_to;

        return $this;
    }

    /**
     * Gets message_content
     *
     * @return string|null
     */
    public function getMessageContent()
    {
        return $this->container['message_content'];
    }

    /**
     * Sets message_content
     *
     * @param string|null $message_content Content of the message
     *
     * @return self
     */
    public function setMessageContent($message_content)
    {
        if (is_null($message_content)) {
            throw new \InvalidArgumentException('non-nullable message_content cannot be null');
        }
        $this->container['message_content'] = $message_content;

        return $this;
    }

    /**
     * Gets external_uid
     *
     * @return string|null
     */
    public function getExternalUid()
    {
        return $this->container['external_uid'];
    }

    /**
     * Sets external_uid
     *
     * @param string|null $external_uid external_uid
     *
     * @return self
     */
    public function setExternalUid($external_uid)
    {
        if (is_null($external_uid)) {
            array_push($this->openAPINullablesSetToNull, 'external_uid');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('external_uid', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['external_uid'] = $external_uid;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string|null
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string|null $title title
     *
     * @return self
     */
    public function setTitle($title)
    {
        if (is_null($title)) {
            array_push($this->openAPINullablesSetToNull, 'title');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('title', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            array_push($this->openAPINullablesSetToNull, 'description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets end_timestamp
     *
     * @return string|null
     */
    public function getEndTimestamp()
    {
        return $this->container['end_timestamp'];
    }

    /**
     * Sets end_timestamp
     *
     * @param string|null $end_timestamp end_timestamp
     *
     * @return self
     */
    public function setEndTimestamp($end_timestamp)
    {
        if (is_null($end_timestamp)) {
            throw new \InvalidArgumentException('non-nullable end_timestamp cannot be null');
        }
        $this->container['end_timestamp'] = $end_timestamp;

        return $this;
    }

    /**
     * Gets organiser
     *
     * @return string|null
     */
    public function getOrganiser()
    {
        return $this->container['organiser'];
    }

    /**
     * Sets organiser
     *
     * @param string|null $organiser organiser
     *
     * @return self
     */
    public function setOrganiser($organiser)
    {
        if (is_null($organiser)) {
            array_push($this->openAPINullablesSetToNull, 'organiser');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('organiser', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['organiser'] = $organiser;

        return $this;
    }

    /**
     * Gets attendee
     *
     * @return string|null
     */
    public function getAttendee()
    {
        return $this->container['attendee'];
    }

    /**
     * Sets attendee
     *
     * @param string|null $attendee attendee
     *
     * @return self
     */
    public function setAttendee($attendee)
    {
        if (is_null($attendee)) {
            array_push($this->openAPINullablesSetToNull, 'attendee');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('attendee', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['attendee'] = $attendee;

        return $this;
    }

    /**
     * Gets location
     *
     * @return string|null
     */
    public function getLocation()
    {
        return $this->container['location'];
    }

    /**
     * Sets location
     *
     * @param string|null $location location
     *
     * @return self
     */
    public function setLocation($location)
    {
        if (is_null($location)) {
            array_push($this->openAPINullablesSetToNull, 'location');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('location', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['location'] = $location;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return string|null
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param string|null $tags tags
     *
     * @return self
     */
    public function setTags($tags)
    {
        if (is_null($tags)) {
            array_push($this->openAPINullablesSetToNull, 'tags');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tags', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets trigger
     *
     * @return string|null
     */
    public function getTrigger()
    {
        return $this->container['trigger'];
    }

    /**
     * Sets trigger
     *
     * @param string|null $trigger trigger
     *
     * @return self
     */
    public function setTrigger($trigger)
    {
        if (is_null($trigger)) {
            array_push($this->openAPINullablesSetToNull, 'trigger');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('trigger', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['trigger'] = $trigger;

        return $this;
    }

    /**
     * Gets action
     *
     * @return string|null
     */
    public function getAction()
    {
        return $this->container['action'];
    }

    /**
     * Sets action
     *
     * @param string|null $action action
     *
     * @return self
     */
    public function setAction($action)
    {
        if (is_null($action)) {
            array_push($this->openAPINullablesSetToNull, 'action');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('action', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['action'] = $action;

        return $this;
    }

    /**
     * Gets reminder_description
     *
     * @return string|null
     */
    public function getReminderDescription()
    {
        return $this->container['reminder_description'];
    }

    /**
     * Sets reminder_description
     *
     * @param string|null $reminder_description reminder_description
     *
     * @return self
     */
    public function setReminderDescription($reminder_description)
    {
        if (is_null($reminder_description)) {
            array_push($this->openAPINullablesSetToNull, 'reminder_description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('reminder_description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['reminder_description'] = $reminder_description;

        return $this;
    }

    /**
     * Gets duration_string
     *
     * @return string|null
     */
    public function getDurationString()
    {
        return $this->container['duration_string'];
    }

    /**
     * Sets duration_string
     *
     * @param string|null $duration_string duration_string
     *
     * @return self
     */
    public function setDurationString($duration_string)
    {
        if (is_null($duration_string)) {
            throw new \InvalidArgumentException('non-nullable duration_string cannot be null');
        }
        $this->container['duration_string'] = $duration_string;

        return $this;
    }

    /**
     * Gets duration_of_event
     *
     * @return float|null
     */
    public function getDurationOfEvent()
    {
        return $this->container['duration_of_event'];
    }

    /**
     * Sets duration_of_event
     *
     * @param float|null $duration_of_event duration_of_event
     *
     * @return self
     */
    public function setDurationOfEvent($duration_of_event)
    {
        if (is_null($duration_of_event)) {
            throw new \InvalidArgumentException('non-nullable duration_of_event cannot be null');
        }
        $this->container['duration_of_event'] = $duration_of_event;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


