<?php
/**
 * TimelineResponseTimelineInnerOneOf1
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Mydex\ApiPdxSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PDX API
 *
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Mydex\ApiPdxSdk\Model;

use \ArrayAccess;
use \Mydex\ApiPdxSdk\ObjectSerializer;

/**
 * TimelineResponseTimelineInnerOneOf1 Class Doc Comment
 *
 * @category Class
 * @description Secure message item
 * @package  Mydex\ApiPdxSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TimelineResponseTimelineInnerOneOf1 implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'TimelineResponse_timeline_inner_oneOf_1';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'id' => 'int',
        'feature_block' => 'string',
        'feature_block_id' => 'string',
        'start_timestamp' => 'string',
        'item_timestamp' => 'int',
        'created_timestamp' => 'int',
        'message_from' => 'string',
        'message_to' => 'string',
        'message_content' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'id' => null,
        'feature_block' => null,
        'feature_block_id' => null,
        'start_timestamp' => null,
        'item_timestamp' => null,
        'created_timestamp' => null,
        'message_from' => null,
        'message_to' => null,
        'message_content' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'id' => false,
        'feature_block' => false,
        'feature_block_id' => false,
        'start_timestamp' => false,
        'item_timestamp' => false,
        'created_timestamp' => false,
        'message_from' => false,
        'message_to' => false,
        'message_content' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'feature_block' => 'feature_block',
        'feature_block_id' => 'feature_block_id',
        'start_timestamp' => 'start_timestamp',
        'item_timestamp' => 'item_timestamp',
        'created_timestamp' => 'created_timestamp',
        'message_from' => 'message_from',
        'message_to' => 'message_to',
        'message_content' => 'message_content'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'feature_block' => 'setFeatureBlock',
        'feature_block_id' => 'setFeatureBlockId',
        'start_timestamp' => 'setStartTimestamp',
        'item_timestamp' => 'setItemTimestamp',
        'created_timestamp' => 'setCreatedTimestamp',
        'message_from' => 'setMessageFrom',
        'message_to' => 'setMessageTo',
        'message_content' => 'setMessageContent'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'feature_block' => 'getFeatureBlock',
        'feature_block_id' => 'getFeatureBlockId',
        'start_timestamp' => 'getStartTimestamp',
        'item_timestamp' => 'getItemTimestamp',
        'created_timestamp' => 'getCreatedTimestamp',
        'message_from' => 'getMessageFrom',
        'message_to' => 'getMessageTo',
        'message_content' => 'getMessageContent'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('feature_block', $data ?? [], null);
        $this->setIfExists('feature_block_id', $data ?? [], null);
        $this->setIfExists('start_timestamp', $data ?? [], null);
        $this->setIfExists('item_timestamp', $data ?? [], null);
        $this->setIfExists('created_timestamp', $data ?? [], null);
        $this->setIfExists('message_from', $data ?? [], null);
        $this->setIfExists('message_to', $data ?? [], null);
        $this->setIfExists('message_content', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets feature_block
     *
     * @return string|null
     */
    public function getFeatureBlock()
    {
        return $this->container['feature_block'];
    }

    /**
     * Sets feature_block
     *
     * @param string|null $feature_block feature_block
     *
     * @return self
     */
    public function setFeatureBlock($feature_block)
    {
        if (is_null($feature_block)) {
            throw new \InvalidArgumentException('non-nullable feature_block cannot be null');
        }
        $this->container['feature_block'] = $feature_block;

        return $this;
    }

    /**
     * Gets feature_block_id
     *
     * @return string|null
     */
    public function getFeatureBlockId()
    {
        return $this->container['feature_block_id'];
    }

    /**
     * Sets feature_block_id
     *
     * @param string|null $feature_block_id feature_block_id
     *
     * @return self
     */
    public function setFeatureBlockId($feature_block_id)
    {
        if (is_null($feature_block_id)) {
            throw new \InvalidArgumentException('non-nullable feature_block_id cannot be null');
        }
        $this->container['feature_block_id'] = $feature_block_id;

        return $this;
    }

    /**
     * Gets start_timestamp
     *
     * @return string|null
     */
    public function getStartTimestamp()
    {
        return $this->container['start_timestamp'];
    }

    /**
     * Sets start_timestamp
     *
     * @param string|null $start_timestamp start_timestamp
     *
     * @return self
     */
    public function setStartTimestamp($start_timestamp)
    {
        if (is_null($start_timestamp)) {
            throw new \InvalidArgumentException('non-nullable start_timestamp cannot be null');
        }
        $this->container['start_timestamp'] = $start_timestamp;

        return $this;
    }

    /**
     * Gets item_timestamp
     *
     * @return int|null
     */
    public function getItemTimestamp()
    {
        return $this->container['item_timestamp'];
    }

    /**
     * Sets item_timestamp
     *
     * @param int|null $item_timestamp item_timestamp
     *
     * @return self
     */
    public function setItemTimestamp($item_timestamp)
    {
        if (is_null($item_timestamp)) {
            throw new \InvalidArgumentException('non-nullable item_timestamp cannot be null');
        }
        $this->container['item_timestamp'] = $item_timestamp;

        return $this;
    }

    /**
     * Gets created_timestamp
     *
     * @return int|null
     */
    public function getCreatedTimestamp()
    {
        return $this->container['created_timestamp'];
    }

    /**
     * Sets created_timestamp
     *
     * @param int|null $created_timestamp created_timestamp
     *
     * @return self
     */
    public function setCreatedTimestamp($created_timestamp)
    {
        if (is_null($created_timestamp)) {
            throw new \InvalidArgumentException('non-nullable created_timestamp cannot be null');
        }
        $this->container['created_timestamp'] = $created_timestamp;

        return $this;
    }

    /**
     * Gets message_from
     *
     * @return string|null
     */
    public function getMessageFrom()
    {
        return $this->container['message_from'];
    }

    /**
     * Sets message_from
     *
     * @param string|null $message_from message_from
     *
     * @return self
     */
    public function setMessageFrom($message_from)
    {
        if (is_null($message_from)) {
            throw new \InvalidArgumentException('non-nullable message_from cannot be null');
        }
        $this->container['message_from'] = $message_from;

        return $this;
    }

    /**
     * Gets message_to
     *
     * @return string|null
     */
    public function getMessageTo()
    {
        return $this->container['message_to'];
    }

    /**
     * Sets message_to
     *
     * @param string|null $message_to message_to
     *
     * @return self
     */
    public function setMessageTo($message_to)
    {
        if (is_null($message_to)) {
            throw new \InvalidArgumentException('non-nullable message_to cannot be null');
        }
        $this->container['message_to'] = $message_to;

        return $this;
    }

    /**
     * Gets message_content
     *
     * @return string|null
     */
    public function getMessageContent()
    {
        return $this->container['message_content'];
    }

    /**
     * Sets message_content
     *
     * @param string|null $message_content message_content
     *
     * @return self
     */
    public function setMessageContent($message_content)
    {
        if (is_null($message_content)) {
            throw new \InvalidArgumentException('non-nullable message_content cannot be null');
        }
        $this->container['message_content'] = $message_content;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


