<?php
/**
 * TimelineItemReferral
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Mydex\ApiPdxSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PDX API
 *
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Mydex\ApiPdxSdk\Model;

use \ArrayAccess;
use \Mydex\ApiPdxSdk\ObjectSerializer;

/**
 * TimelineItemReferral Class Doc Comment
 *
 * @category Class
 * @description A single timeline item representing a referral
 * @package  Mydex\ApiPdxSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TimelineItemReferral implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'TimelineItemReferral';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'feature_block' => 'string',
        'feature_block_id' => 'int',
        'instance' => 'string',
        'source' => 'string',
        'created_timestamp' => 'int',
        'updated_timestamp' => 'int',
        'service_id' => 'int',
        'service_name' => 'string',
        'service_description' => 'string',
        'service_url' => 'string',
        'service_email' => 'string',
        'contact_name' => 'string',
        'contact_title' => 'string',
        'contact_number' => 'string',
        'referrer_name' => 'string',
        'status' => 'string',
        'external_id' => 'string',
        'start_time' => 'int',
        'end_time' => 'int',
        'is_processed' => 'bool',
        'complete_time' => 'int',
        'memo' => 'string',
        'duration' => 'string',
        'referree_background' => 'string',
        'referree_requirements' => 'string',
        'referree_availability' => 'object',
        'type' => 'string',
        'start_timestamp' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'feature_block' => null,
        'feature_block_id' => null,
        'instance' => null,
        'source' => null,
        'created_timestamp' => 'int64',
        'updated_timestamp' => 'int64',
        'service_id' => null,
        'service_name' => null,
        'service_description' => null,
        'service_url' => null,
        'service_email' => null,
        'contact_name' => null,
        'contact_title' => null,
        'contact_number' => null,
        'referrer_name' => null,
        'status' => null,
        'external_id' => null,
        'start_time' => 'int64',
        'end_time' => 'int64',
        'is_processed' => null,
        'complete_time' => null,
        'memo' => null,
        'duration' => null,
        'referree_background' => null,
        'referree_requirements' => null,
        'referree_availability' => null,
        'type' => null,
        'start_timestamp' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'feature_block' => false,
        'feature_block_id' => false,
        'instance' => false,
        'source' => false,
        'created_timestamp' => false,
        'updated_timestamp' => false,
        'service_id' => false,
        'service_name' => false,
        'service_description' => false,
        'service_url' => false,
        'service_email' => false,
        'contact_name' => false,
        'contact_title' => false,
        'contact_number' => false,
        'referrer_name' => false,
        'status' => false,
        'external_id' => false,
        'start_time' => false,
        'end_time' => false,
        'is_processed' => false,
        'complete_time' => false,
        'memo' => false,
        'duration' => false,
        'referree_background' => false,
        'referree_requirements' => false,
        'referree_availability' => false,
        'type' => false,
        'start_timestamp' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'feature_block' => 'feature_block',
        'feature_block_id' => 'feature_block_id',
        'instance' => 'instance',
        'source' => 'source',
        'created_timestamp' => 'created_timestamp',
        'updated_timestamp' => 'updated_timestamp',
        'service_id' => 'service_id',
        'service_name' => 'service_name',
        'service_description' => 'service_description',
        'service_url' => 'service_url',
        'service_email' => 'service_email',
        'contact_name' => 'contact_name',
        'contact_title' => 'contact_title',
        'contact_number' => 'contact_number',
        'referrer_name' => 'referrer_name',
        'status' => 'status',
        'external_id' => 'external_id',
        'start_time' => 'start_time',
        'end_time' => 'end_time',
        'is_processed' => 'is_processed',
        'complete_time' => 'complete_time',
        'memo' => 'memo',
        'duration' => 'duration',
        'referree_background' => 'referree_background',
        'referree_requirements' => 'referree_requirements',
        'referree_availability' => 'referree_availability',
        'type' => 'type',
        'start_timestamp' => 'start_timestamp'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'feature_block' => 'setFeatureBlock',
        'feature_block_id' => 'setFeatureBlockId',
        'instance' => 'setInstance',
        'source' => 'setSource',
        'created_timestamp' => 'setCreatedTimestamp',
        'updated_timestamp' => 'setUpdatedTimestamp',
        'service_id' => 'setServiceId',
        'service_name' => 'setServiceName',
        'service_description' => 'setServiceDescription',
        'service_url' => 'setServiceUrl',
        'service_email' => 'setServiceEmail',
        'contact_name' => 'setContactName',
        'contact_title' => 'setContactTitle',
        'contact_number' => 'setContactNumber',
        'referrer_name' => 'setReferrerName',
        'status' => 'setStatus',
        'external_id' => 'setExternalId',
        'start_time' => 'setStartTime',
        'end_time' => 'setEndTime',
        'is_processed' => 'setIsProcessed',
        'complete_time' => 'setCompleteTime',
        'memo' => 'setMemo',
        'duration' => 'setDuration',
        'referree_background' => 'setReferreeBackground',
        'referree_requirements' => 'setReferreeRequirements',
        'referree_availability' => 'setReferreeAvailability',
        'type' => 'setType',
        'start_timestamp' => 'setStartTimestamp'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'feature_block' => 'getFeatureBlock',
        'feature_block_id' => 'getFeatureBlockId',
        'instance' => 'getInstance',
        'source' => 'getSource',
        'created_timestamp' => 'getCreatedTimestamp',
        'updated_timestamp' => 'getUpdatedTimestamp',
        'service_id' => 'getServiceId',
        'service_name' => 'getServiceName',
        'service_description' => 'getServiceDescription',
        'service_url' => 'getServiceUrl',
        'service_email' => 'getServiceEmail',
        'contact_name' => 'getContactName',
        'contact_title' => 'getContactTitle',
        'contact_number' => 'getContactNumber',
        'referrer_name' => 'getReferrerName',
        'status' => 'getStatus',
        'external_id' => 'getExternalId',
        'start_time' => 'getStartTime',
        'end_time' => 'getEndTime',
        'is_processed' => 'getIsProcessed',
        'complete_time' => 'getCompleteTime',
        'memo' => 'getMemo',
        'duration' => 'getDuration',
        'referree_background' => 'getReferreeBackground',
        'referree_requirements' => 'getReferreeRequirements',
        'referree_availability' => 'getReferreeAvailability',
        'type' => 'getType',
        'start_timestamp' => 'getStartTimestamp'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const STATUS_REFERRED = 'Referred';
    public const STATUS_IN_PROGRESS = 'In Progress';
    public const STATUS_ACCEPTED = 'Accepted';
    public const STATUS_REJECTED = 'Rejected';
    public const STATUS_UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_REFERRED,
            self::STATUS_IN_PROGRESS,
            self::STATUS_ACCEPTED,
            self::STATUS_REJECTED,
            self::STATUS_UNKNOWN_DEFAULT_OPEN_API,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('feature_block', $data ?? [], null);
        $this->setIfExists('feature_block_id', $data ?? [], null);
        $this->setIfExists('instance', $data ?? [], null);
        $this->setIfExists('source', $data ?? [], null);
        $this->setIfExists('created_timestamp', $data ?? [], null);
        $this->setIfExists('updated_timestamp', $data ?? [], null);
        $this->setIfExists('service_id', $data ?? [], null);
        $this->setIfExists('service_name', $data ?? [], null);
        $this->setIfExists('service_description', $data ?? [], null);
        $this->setIfExists('service_url', $data ?? [], null);
        $this->setIfExists('service_email', $data ?? [], null);
        $this->setIfExists('contact_name', $data ?? [], null);
        $this->setIfExists('contact_title', $data ?? [], null);
        $this->setIfExists('contact_number', $data ?? [], null);
        $this->setIfExists('referrer_name', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('external_id', $data ?? [], null);
        $this->setIfExists('start_time', $data ?? [], null);
        $this->setIfExists('end_time', $data ?? [], null);
        $this->setIfExists('is_processed', $data ?? [], null);
        $this->setIfExists('complete_time', $data ?? [], null);
        $this->setIfExists('memo', $data ?? [], null);
        $this->setIfExists('duration', $data ?? [], null);
        $this->setIfExists('referree_background', $data ?? [], null);
        $this->setIfExists('referree_requirements', $data ?? [], null);
        $this->setIfExists('referree_availability', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('start_timestamp', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets feature_block
     *
     * @return string|null
     */
    public function getFeatureBlock()
    {
        return $this->container['feature_block'];
    }

    /**
     * Sets feature_block
     *
     * @param string|null $feature_block Type of feature block this timeline item belongs to
     *
     * @return self
     */
    public function setFeatureBlock($feature_block)
    {
        if (is_null($feature_block)) {
            throw new \InvalidArgumentException('non-nullable feature_block cannot be null');
        }
        $this->container['feature_block'] = $feature_block;

        return $this;
    }

    /**
     * Gets feature_block_id
     *
     * @return int|null
     */
    public function getFeatureBlockId()
    {
        return $this->container['feature_block_id'];
    }

    /**
     * Sets feature_block_id
     *
     * @param int|null $feature_block_id ID of the feature block record i.e. the referral id
     *
     * @return self
     */
    public function setFeatureBlockId($feature_block_id)
    {
        if (is_null($feature_block_id)) {
            throw new \InvalidArgumentException('non-nullable feature_block_id cannot be null');
        }
        $this->container['feature_block_id'] = $feature_block_id;

        return $this;
    }

    /**
     * Gets instance
     *
     * @return string|null
     */
    public function getInstance()
    {
        return $this->container['instance'];
    }

    /**
     * Sets instance
     *
     * @param string|null $instance instance
     *
     * @return self
     */
    public function setInstance($instance)
    {
        if (is_null($instance)) {
            throw new \InvalidArgumentException('non-nullable instance cannot be null');
        }
        $this->container['instance'] = $instance;

        return $this;
    }

    /**
     * Gets source
     *
     * @return string|null
     */
    public function getSource()
    {
        return $this->container['source'];
    }

    /**
     * Sets source
     *
     * @param string|null $source The context within which this record was created i.e. the specific connection
     *
     * @return self
     */
    public function setSource($source)
    {
        if (is_null($source)) {
            throw new \InvalidArgumentException('non-nullable source cannot be null');
        }
        $this->container['source'] = $source;

        return $this;
    }

    /**
     * Gets created_timestamp
     *
     * @return int|null
     */
    public function getCreatedTimestamp()
    {
        return $this->container['created_timestamp'];
    }

    /**
     * Sets created_timestamp
     *
     * @param int|null $created_timestamp created_timestamp
     *
     * @return self
     */
    public function setCreatedTimestamp($created_timestamp)
    {
        if (is_null($created_timestamp)) {
            throw new \InvalidArgumentException('non-nullable created_timestamp cannot be null');
        }
        $this->container['created_timestamp'] = $created_timestamp;

        return $this;
    }

    /**
     * Gets updated_timestamp
     *
     * @return int|null
     */
    public function getUpdatedTimestamp()
    {
        return $this->container['updated_timestamp'];
    }

    /**
     * Sets updated_timestamp
     *
     * @param int|null $updated_timestamp updated_timestamp
     *
     * @return self
     */
    public function setUpdatedTimestamp($updated_timestamp)
    {
        if (is_null($updated_timestamp)) {
            throw new \InvalidArgumentException('non-nullable updated_timestamp cannot be null');
        }
        $this->container['updated_timestamp'] = $updated_timestamp;

        return $this;
    }

    /**
     * Gets service_id
     *
     * @return int|null
     */
    public function getServiceId()
    {
        return $this->container['service_id'];
    }

    /**
     * Sets service_id
     *
     * @param int|null $service_id The id of the service that the referral relates to
     *
     * @return self
     */
    public function setServiceId($service_id)
    {
        if (is_null($service_id)) {
            throw new \InvalidArgumentException('non-nullable service_id cannot be null');
        }
        $this->container['service_id'] = $service_id;

        return $this;
    }

    /**
     * Gets service_name
     *
     * @return string|null
     */
    public function getServiceName()
    {
        return $this->container['service_name'];
    }

    /**
     * Sets service_name
     *
     * @param string|null $service_name service_name
     *
     * @return self
     */
    public function setServiceName($service_name)
    {
        if (is_null($service_name)) {
            throw new \InvalidArgumentException('non-nullable service_name cannot be null');
        }
        $this->container['service_name'] = $service_name;

        return $this;
    }

    /**
     * Gets service_description
     *
     * @return string|null
     */
    public function getServiceDescription()
    {
        return $this->container['service_description'];
    }

    /**
     * Sets service_description
     *
     * @param string|null $service_description service_description
     *
     * @return self
     */
    public function setServiceDescription($service_description)
    {
        if (is_null($service_description)) {
            throw new \InvalidArgumentException('non-nullable service_description cannot be null');
        }
        $this->container['service_description'] = $service_description;

        return $this;
    }

    /**
     * Gets service_url
     *
     * @return string|null
     */
    public function getServiceUrl()
    {
        return $this->container['service_url'];
    }

    /**
     * Sets service_url
     *
     * @param string|null $service_url service_url
     *
     * @return self
     */
    public function setServiceUrl($service_url)
    {
        if (is_null($service_url)) {
            throw new \InvalidArgumentException('non-nullable service_url cannot be null');
        }
        $this->container['service_url'] = $service_url;

        return $this;
    }

    /**
     * Gets service_email
     *
     * @return string|null
     */
    public function getServiceEmail()
    {
        return $this->container['service_email'];
    }

    /**
     * Sets service_email
     *
     * @param string|null $service_email service_email
     *
     * @return self
     */
    public function setServiceEmail($service_email)
    {
        if (is_null($service_email)) {
            throw new \InvalidArgumentException('non-nullable service_email cannot be null');
        }
        $this->container['service_email'] = $service_email;

        return $this;
    }

    /**
     * Gets contact_name
     *
     * @return string|null
     */
    public function getContactName()
    {
        return $this->container['contact_name'];
    }

    /**
     * Sets contact_name
     *
     * @param string|null $contact_name contact_name
     *
     * @return self
     */
    public function setContactName($contact_name)
    {
        if (is_null($contact_name)) {
            throw new \InvalidArgumentException('non-nullable contact_name cannot be null');
        }
        $this->container['contact_name'] = $contact_name;

        return $this;
    }

    /**
     * Gets contact_title
     *
     * @return string|null
     */
    public function getContactTitle()
    {
        return $this->container['contact_title'];
    }

    /**
     * Sets contact_title
     *
     * @param string|null $contact_title contact_title
     *
     * @return self
     */
    public function setContactTitle($contact_title)
    {
        if (is_null($contact_title)) {
            throw new \InvalidArgumentException('non-nullable contact_title cannot be null');
        }
        $this->container['contact_title'] = $contact_title;

        return $this;
    }

    /**
     * Gets contact_number
     *
     * @return string|null
     */
    public function getContactNumber()
    {
        return $this->container['contact_number'];
    }

    /**
     * Sets contact_number
     *
     * @param string|null $contact_number contact_number
     *
     * @return self
     */
    public function setContactNumber($contact_number)
    {
        if (is_null($contact_number)) {
            throw new \InvalidArgumentException('non-nullable contact_number cannot be null');
        }
        $this->container['contact_number'] = $contact_number;

        return $this;
    }

    /**
     * Gets referrer_name
     *
     * @return string|null
     */
    public function getReferrerName()
    {
        return $this->container['referrer_name'];
    }

    /**
     * Sets referrer_name
     *
     * @param string|null $referrer_name referrer_name
     *
     * @return self
     */
    public function setReferrerName($referrer_name)
    {
        if (is_null($referrer_name)) {
            throw new \InvalidArgumentException('non-nullable referrer_name cannot be null');
        }
        $this->container['referrer_name'] = $referrer_name;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            $status = self::STATUS_UNKNOWN_DEFAULT_OPEN_API;
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets external_id
     *
     * @return string|null
     */
    public function getExternalId()
    {
        return $this->container['external_id'];
    }

    /**
     * Sets external_id
     *
     * @param string|null $external_id external_id
     *
     * @return self
     */
    public function setExternalId($external_id)
    {
        if (is_null($external_id)) {
            throw new \InvalidArgumentException('non-nullable external_id cannot be null');
        }
        $this->container['external_id'] = $external_id;

        return $this;
    }

    /**
     * Gets start_time
     *
     * @return int|null
     */
    public function getStartTime()
    {
        return $this->container['start_time'];
    }

    /**
     * Sets start_time
     *
     * @param int|null $start_time start_time
     *
     * @return self
     */
    public function setStartTime($start_time)
    {
        if (is_null($start_time)) {
            throw new \InvalidArgumentException('non-nullable start_time cannot be null');
        }
        $this->container['start_time'] = $start_time;

        return $this;
    }

    /**
     * Gets end_time
     *
     * @return int|null
     */
    public function getEndTime()
    {
        return $this->container['end_time'];
    }

    /**
     * Sets end_time
     *
     * @param int|null $end_time end_time
     *
     * @return self
     */
    public function setEndTime($end_time)
    {
        if (is_null($end_time)) {
            throw new \InvalidArgumentException('non-nullable end_time cannot be null');
        }
        $this->container['end_time'] = $end_time;

        return $this;
    }

    /**
     * Gets is_processed
     *
     * @return bool|null
     */
    public function getIsProcessed()
    {
        return $this->container['is_processed'];
    }

    /**
     * Sets is_processed
     *
     * @param bool|null $is_processed is_processed
     *
     * @return self
     */
    public function setIsProcessed($is_processed)
    {
        if (is_null($is_processed)) {
            throw new \InvalidArgumentException('non-nullable is_processed cannot be null');
        }
        $this->container['is_processed'] = $is_processed;

        return $this;
    }

    /**
     * Gets complete_time
     *
     * @return int|null
     */
    public function getCompleteTime()
    {
        return $this->container['complete_time'];
    }

    /**
     * Sets complete_time
     *
     * @param int|null $complete_time complete_time
     *
     * @return self
     */
    public function setCompleteTime($complete_time)
    {
        if (is_null($complete_time)) {
            throw new \InvalidArgumentException('non-nullable complete_time cannot be null');
        }
        $this->container['complete_time'] = $complete_time;

        return $this;
    }

    /**
     * Gets memo
     *
     * @return string|null
     */
    public function getMemo()
    {
        return $this->container['memo'];
    }

    /**
     * Sets memo
     *
     * @param string|null $memo memo
     *
     * @return self
     */
    public function setMemo($memo)
    {
        if (is_null($memo)) {
            throw new \InvalidArgumentException('non-nullable memo cannot be null');
        }
        $this->container['memo'] = $memo;

        return $this;
    }

    /**
     * Gets duration
     *
     * @return string|null
     */
    public function getDuration()
    {
        return $this->container['duration'];
    }

    /**
     * Sets duration
     *
     * @param string|null $duration duration
     *
     * @return self
     */
    public function setDuration($duration)
    {
        if (is_null($duration)) {
            throw new \InvalidArgumentException('non-nullable duration cannot be null');
        }
        $this->container['duration'] = $duration;

        return $this;
    }

    /**
     * Gets referree_background
     *
     * @return string|null
     */
    public function getReferreeBackground()
    {
        return $this->container['referree_background'];
    }

    /**
     * Sets referree_background
     *
     * @param string|null $referree_background referree_background
     *
     * @return self
     */
    public function setReferreeBackground($referree_background)
    {
        if (is_null($referree_background)) {
            throw new \InvalidArgumentException('non-nullable referree_background cannot be null');
        }
        $this->container['referree_background'] = $referree_background;

        return $this;
    }

    /**
     * Gets referree_requirements
     *
     * @return string|null
     */
    public function getReferreeRequirements()
    {
        return $this->container['referree_requirements'];
    }

    /**
     * Sets referree_requirements
     *
     * @param string|null $referree_requirements referree_requirements
     *
     * @return self
     */
    public function setReferreeRequirements($referree_requirements)
    {
        if (is_null($referree_requirements)) {
            throw new \InvalidArgumentException('non-nullable referree_requirements cannot be null');
        }
        $this->container['referree_requirements'] = $referree_requirements;

        return $this;
    }

    /**
     * Gets referree_availability
     *
     * @return object|null
     */
    public function getReferreeAvailability()
    {
        return $this->container['referree_availability'];
    }

    /**
     * Sets referree_availability
     *
     * @param object|null $referree_availability Availability of the referree in AM/PM slots
     *
     * @return self
     */
    public function setReferreeAvailability($referree_availability)
    {
        if (is_null($referree_availability)) {
            throw new \InvalidArgumentException('non-nullable referree_availability cannot be null');
        }
        $this->container['referree_availability'] = $referree_availability;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string|null $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets start_timestamp
     *
     * @return string|null
     */
    public function getStartTimestamp()
    {
        return $this->container['start_timestamp'];
    }

    /**
     * Sets start_timestamp
     *
     * @param string|null $start_timestamp start_timestamp
     *
     * @return self
     */
    public function setStartTimestamp($start_timestamp)
    {
        if (is_null($start_timestamp)) {
            throw new \InvalidArgumentException('non-nullable start_timestamp cannot be null');
        }
        $this->container['start_timestamp'] = $start_timestamp;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


