<?php
/**
 * ReferralsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Mydex\ApiPdxSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PDX API
 *
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Mydex\ApiPdxSdk\Test\Api;

use \Mydex\ApiPdxSdk\Configuration;
use \Mydex\ApiPdxSdk\ApiException;
use \Mydex\ApiPdxSdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ReferralsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Mydex\ApiPdxSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ReferralsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getAllReferrals
     *
     * Retrieve rall referrals for a given member..
     *
     */
    public function testGetAllReferrals()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSingleReferral
     *
     * Retrieve a single referral by id for a given member..
     *
     */
    public function testGetSingleReferral()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postSelfReferral
     *
     * Supports self-referral..
     *
     */
    public function testPostSelfReferral()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateReferralStatus
     *
     * Supports updating the status of a referral..
     *
     */
    public function testUpdateReferralStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
