<?php
/**
 * SecureMessagesApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Mydex\ApiPdxSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PDX API
 *
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Mydex\ApiPdxSdk\Test\Api;

use \Mydex\ApiPdxSdk\Configuration;
use \Mydex\ApiPdxSdk\ApiException;
use \Mydex\ApiPdxSdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SecureMessagesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Mydex\ApiPdxSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SecureMessagesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getSecureMessageConversation
     *
     * Retrieve all secure messages for a given conversation..
     *
     */
    public function testGetSecureMessageConversation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postSecureMessageReceive
     *
     * Supports sending a message to the member's PDS..
     *
     */
    public function testPostSecureMessageReceive()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postSecureMessageSend
     *
     * Supports sending a message from the member's PDS..
     *
     */
    public function testPostSecureMessageSend()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
